### ISSUE TITLE
MemoryError while using category grouping in ACVTree

### ISSUE THREAD

**Issue by CBoidot** [salimamoukou/acv00#8]
I wanted to use your TreeSHAP computation, because some variable in my dataset should be linked.
I selected a small model (one tree... with a thousand leaves), used on a dataset with 23 features.
I do not understand the size of the arrays used in the computation : it produces MemoryErrors, even when I try to use very small data : only one tree of my random forest, 20 data as background for the explainer, and 3 data to explain.

"tree = rf.estimators_[0]
acvtree = ACVTree(tree, train.iloc[:20])
cats = [[0],[1,4],[2,5],[3,6],
        [7,15],[8,16],[9,17],[10,18],[11,19],[12,20],[13,21],[14,22]]
sv = acvtree.shap_values(test.iloc[:3],cats)"
"MemoryError: Unable to allocate 161. GiB for an array with shape (1196, 131072, 3, 23, 2) and data type float64"

I can explain any number in this shape except 131072 (1192 is the number of leaves, two must is the number of outputs of the classifier).
Do you have any idea what I should do to mitigate this problem ?

**Comment by salimamoukou** [comment]
Sorry for the late reply. In fact, it's because the code is currently in Cython, and to parallelize the calculation of SV with our algorithm, which is exponential as a function of depth (2^depth) instead of the number of variables (2^d), we store large matrices in the order of magnitude 2^depth.


Before implementing this part in C++ to efficiently parallelize without the storage of large matrices, there are two options:

- Reduce the depth if it does not significantly affect performance (typically depth < 10)
- As stated in the readme, you can also opt to remove parallelization (see below)

![scaling_problem](https://user-images.githubusercontent.com/40361886/216561651-215c29c7-8e96-491e-8e28-6f78f39db462.png)

**Comment by CBoidot** [comment]
As it is a model I do not want to change, I will keep to the second option (which works well in my case).
Thank you !
